src/models/Region.php
добавлен геттер на получение списка регионов сгруппированного по странам
=> issue #1949, Дилеры, список дилеров и карточка

src/models/Region.php
=> Issue #1949

migrations/m181114_104202_tbl_eab_temp.php
closes infotech-ru/autocrm#6279
=> infotech-ru/dsfsubaru#2319

migrations/m181116_152010_alias_add_is_new.php, src/models/ModelAlias.php, src/models/aeb/AEBRegion.php, tests/unit/models/ModelAliasTest.php
closes infotech-ru/autocrm#6298
=> autocrm-6298 РефБД, алиасы

migrations/m181226_111201_tbl_add_brand_string.php, src/models/aeb/BrandMapping.php, src/models/aeb/TemporaryAEBRegionData.php
closes infotech-ru/autocrm#6510
=> autocrm-6510 Импорт АЕБ (AEB) - маппинг брендов

migrations/m190329_142704_add_code_in_vehicle_option_group.php, src/models/VehicleOptionGroup.php, tests/unit/models/VehicleOptionGroupTest.php
=> issue infotech-ru/mysales#302

migrations/m200310_134130_eqt_autoru_mark_map.php, src/models/aeb/BrandMapping.php, src/models/autoru/AutoruMark.php, src/models/autoru/AutoruMarkMap.php, src/models/autoru/queries/AutoruMarkMapQuery.php
close infotech-ru/warehouse#2733
=> close infotech-ru/warehouse#2733

migrations/m210201_093031_alter_table_regions_add_column_iso_code.php, src/models/Region.php, tests/config.php, tests/unit/models/RegionTest.php
=> issue dsfsubaru#7366

migrations/m210216_130442_add_english_name_column_in_cities_table.php, src/models/City.php, tests/unit/models/CityTest.php
part of infotech-ru/dsfsubaru#7384
=> Haval 7384

migrations/m210425_181044_create_bank_table.php, migrations/m210425_181118_create_credit_program_table.php, migrations/m210425_185720_create_credit_program_option_table.php, migrations/m210425_185732_create_credit_program_brand_table.php, migrations/m210425_185743_create_credit_program_model_table.php, migrations/m210425_185754_create_credit_program_generation_table.php, migrations/m210425_185808_create_credit_program_series_table.php, migrations/m210425_185819_create_credit_program_modification_table.php, migrations/m210425_185832_create_credit_program_equipment_table.php, src/models/CreditBank.php, src/models/CreditProgram.php, src/models/CreditProgramBrand.php, src/models/CreditProgramEquipment.php, src/models/CreditProgramGeneration.php, src/models/CreditProgramModel.php, src/models/CreditProgramModification.php, src/models/CreditProgramOption.php, src/models/CreditProgramSeries.php
issue infotech-ru/autocrm#10511
=> issue infotech-ru/autocrm#10511

src/models/Generation.php, tests/unit/models/GenerationTest.php
=> #20 Поколения, загрузка файлов

migrations/m211126_105623_alter_table_model_alias_add_order.php, src/models/ModelAlias.php, tests/fixtures/data/model_alias.php, tests/unit/models/ModelAliasTest.php
=> issue #9687

migrations/m160719_144216_drop_body_code.php, src/Module.php, src/models/Country.php, src/models/EquipmentModelImageQuery.php, src/models/VehicleVerificationProgramQuery.php, src/models/autoru/AutoruFolder.php, src/models/autoru/AutoruLkt.php, src/models/autoru/AutoruModification.php
=> add country

src/models/Status.php, tests/unit/models/StatusTest.php
=> infotech-ru/dsfsubaru#10943 Субару, склад, прием на склад

src/models/Status.php
issue https://github.com/infotech-ru/dsfsubaru/issues/11211
=> Dsfsubaru 11211

.github/workflows/ci.yml, migrations/m220804_120205_vehicle_verification_program_color.php, src/models/VehicleVerificationProgram.php, tests/unit/models/VehicleVerificationProgramTest.php
closes infotech-ru/dsfsubaru#12114
=> closes infotech-ru/dsfsubaru#12114

src/models/Brand.php, tests/unit/models/BrandTest.php
depends infotech-ru/dsfsubaru#12298
=> infotech-ru/dsfsubaru#12298 Создание бренда Tank

migrations/m221005_133405_add_columns_table_russian_name.php, src/models/RussianName.php, tests/unit/models/RussianNameTest.php
https://github.com/infotech-ru/dsfsubaru/issues/12248
=> issue-12248

src/models/Brand.php
https://github.com/infotech-ru/dsfsubaru/issues/11912
=> issue-11912

src/models/Brand.php
Добавлены константы для задачи: настройка API для передачи лидов в Оркестратор
=> Issue 11912

migrations/m221207_110447_create_model_country_table.php, src/models/Model.php, src/models/ModelCountry.php, src/models/ModelQuery.php
=> issue infotech-ru/refapp#30

src/models/ModelQuery.php
=> issue #13417

composer.json, migrations/m230127_141815_add_equipment_id_in_model_alias.php, migrations/m230127_142334_create_model_alias_country_table.php, src/models/ModelAlias.php, src/models/ModelQuery.php, tests/unit/models/ModelAliasTest.php
https://github.com/infotech-ru/refapp/issues/34
=> Refapp #34

src/models/ModelAliasQuery.php
issue infotech-ru/dsfsubaru#13801
=> issue infotech-ru/dsfsubaru#13801

src/models/GenerationFile.php, tests/unit/models/GenerationFileTest.php
=> issue infotech-ru/refapp#44

migrations/m230724_134709_create_autoru_folder_models_table.php, src/models/autoru/AutoruFolder.php, src/models/autoru/AutoruFolderModels.php
Добавил таблицу для привязки реф.моделей к моделям справочника автору
=> issue-wh-5669

src/models/Brand.php
issue infotech-ru/dsfsubaru#16941
=> issue infotech-ru/dsfsubaru#16941

src/models/Brand.php
=> добавлены новые бренды

migrations/m240315_103926_add_column_table_russian_name.php, src/models/RussianName.php, tests/unit/models/RussianNameTest.php
=> #haval-19919 Дедупликация

migrations/m240613_130816_add_column_to_autoru_maps.php, src/models/autoru/AutoruFolder.php
=> issue-dnm-21900

migrations/m240620_111749_change_brand_id_in_vehicle_verification_program.php
issue infotech-ru/dsfsubaru#22088
=> issue infotech-ru/dsfsubaru#22088

src/models/Brand.php
https://infotech.zetep.com/board/5/231/infotech-ru/refapp/issue/125
=> refapp-125

migrations/m241029_071842_add_autoru_cm_expert_configuration_map.php, src/models/autoru/AutoruCmExpertConfigurationMap.php
=> issue-26042

src/models/Brand.php
=> issue #26212

migrations/m250411_100647_create_sls_toyota_brand_table.php, src/models/slstoyota/Brand.php, src/models/slstoyota/queries/BrandQuery.php
issue infotech-ru/autocrm#17203
=> issue infotech-ru/autocrm#17203

src/components/JsonTarget.php
https://github.com/infotech-ru/dsfsubaru/issues/32910
=> #32910 Добавление уникального error-id в обработку исключений

src/models/autoru/AutoruComplectation.php, src/models/autoru/AutoruComplectationMapped.php, src/models/autoru/AutoruComplectationRelation.php
=> issue-dnm-36261

migrations/m250905_112156_alter_table_eqt_autoru_mark.php
=> issue-wh-6264
